"""empty message

Revision ID: 4f7d8fb45ba3
Revises: f69af20b9302
Create Date: 2025-07-01 23:37:30.594537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7d8fb45ba3'
down_revision = 'f69af20b9302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('time_taken', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('points', sa.Integer(), server_default='0', nullable=False))
        batch_op.drop_constraint(batch_op.f('games_winner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('winner_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_points', sa.Integer(), server_default='0', nullable=False))
        batch_op.drop_column('rank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('experience_points')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('games_winner_id_fkey'), 'users', ['winner_id'], ['id'])
        batch_op.drop_column('points')
        batch_op.drop_column('time_taken')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('user_id')

    op.create_table('scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_taken', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('scores_game_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('scores_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scores_pkey'))
    )
    # ### end Alembic commands ###
